version: '3'

services:
  laravel-docker:
    container_name: laravel-sso
    build:
      context: .
      dockerfile: Dockerfile
    command: 'php artisan serve --host=0.0.0.0'
    volumes:
      - .:/app
    ports:
      - 9128:8000
  
  laravel-react:
    container_name: react-laravel
    build:
      context: .
      dockerfile: Dockerfile
    command: 'npm run dev'
    volumes:
      - .:/app
    ports:
      - 5173:5173
    depends_on:
      - laravel-docker
